# Generated by Django 3.0.5 on 2020-08-07 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_booking', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of booking')),
                ('date_starting', models.DateField(verbose_name='Date of start of tenancy')),
                ('date_ending', models.DateField(null=True, verbose_name='Date of end of tenancy')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Is payment made')),
            ],
            options={
                'ordering': ('time_booking', 'date_starting', 'property'),
            },
        ),
    ]
